--
-- PostgreSQL database dump
--

\restrict T4U91h8k9jY8R0vujXjam733Ug4pxaC6brHkBMy6hqkZpA8YaPaiNFohRM320uP

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg12+1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: washing_machine_center_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO washing_machine_center_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: reservation; Type: TABLE; Schema: public; Owner: washing_machine_center_user
--

CREATE TABLE public.reservation (
    reservationid integer NOT NULL,
    createdat timestamp(6) without time zone NOT NULL,
    date date NOT NULL,
    endtime character varying(255) NOT NULL,
    starttime character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    washduration integer NOT NULL,
    washtype character varying(255),
    studentid integer NOT NULL,
    machineid integer NOT NULL,
    price double precision,
    start_time character varying(10) DEFAULT '00:00'::character varying NOT NULL,
    end_time character varying(10) DEFAULT '00:00'::character varying NOT NULL,
    wash_type character varying(255),
    wash_duration integer
);


ALTER TABLE public.reservation OWNER TO washing_machine_center_user;

--
-- Name: reservation_reservationid_seq; Type: SEQUENCE; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE public.reservation ALTER COLUMN reservationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_reservationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: washing_machine_center_user
--

CREATE TABLE public.student (
    "studentId" integer NOT NULL,
    balance double precision NOT NULL,
    email character varying(255),
    nachname character varying(255),
    password character varying(255),
    vorname character varying(255)
);


ALTER TABLE public.student OWNER TO washing_machine_center_user;

--
-- Name: student_studentId_seq; Type: SEQUENCE; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE public.student ALTER COLUMN "studentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."student_studentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: washmachine; Type: TABLE; Schema: public; Owner: washing_machine_center_user
--

CREATE TABLE public.washmachine (
    machineid integer NOT NULL,
    isopen boolean,
    machinenr character varying(255) NOT NULL,
    status character varying(255),
    timeremaining integer,
    users character varying(255),
    type character varying(255) DEFAULT 'washer'::character varying
);


ALTER TABLE public.washmachine OWNER TO washing_machine_center_user;

--
-- Name: washmachine_machineid_seq; Type: SEQUENCE; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE public.washmachine ALTER COLUMN machineid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.washmachine_machineid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: reservation; Type: TABLE DATA; Schema: public; Owner: washing_machine_center_user
--

COPY public.reservation (reservationid, createdat, date, endtime, starttime, status, washduration, washtype, studentid, machineid, price, start_time, end_time, wash_type, wash_duration) FROM stdin;
\.


--
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: washing_machine_center_user
--

COPY public.student ("studentId", balance, email, nachname, password, vorname) FROM stdin;
\.


--
-- Data for Name: washmachine; Type: TABLE DATA; Schema: public; Owner: washing_machine_center_user
--

COPY public.washmachine (machineid, isopen, machinenr, status, timeremaining, users, type) FROM stdin;
1	t	Washer 1	Available	\N	\N	washer
3	t	Washer 3	Available	\N	\N	washer
4	f	Washer 4	Out of Order	\N	\N	washer
5	t	Washer 5	Available	\N	\N	washer
2	t	Washer 2	Available	\N	\N	washer
6	t	Washer 6	Available	\N	\N	washer
7	\N	Dryer 1	Available	\N	\N	dryer
8	\N	Dryer 2	Available	\N	\N	dryer
9	\N	Dryer 3	Available	\N	\N	dryer
10	\N	Dryer 4	Available	\N	\N	dryer
11	\N	Dryer 5	Available	\N	\N	dryer
12	\N	Dryer 6	Available	\N	\N	dryer
\.


--
-- Name: reservation_reservationid_seq; Type: SEQUENCE SET; Schema: public; Owner: washing_machine_center_user
--

SELECT pg_catalog.setval('public.reservation_reservationid_seq', 1, false);


--
-- Name: student_studentId_seq; Type: SEQUENCE SET; Schema: public; Owner: washing_machine_center_user
--

SELECT pg_catalog.setval('public."student_studentId_seq"', 1, false);


--
-- Name: washmachine_machineid_seq; Type: SEQUENCE SET; Schema: public; Owner: washing_machine_center_user
--

SELECT pg_catalog.setval('public.washmachine_machineid_seq', 34, true);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (reservationid);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY ("studentId");


--
-- Name: washmachine washmachine_pkey; Type: CONSTRAINT; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE ONLY public.washmachine
    ADD CONSTRAINT washmachine_pkey PRIMARY KEY (machineid);


--
-- Name: reservation fk6tqmgj4251hjtgnxe16aql4x6; Type: FK CONSTRAINT; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk6tqmgj4251hjtgnxe16aql4x6 FOREIGN KEY (studentid) REFERENCES public.student("studentId");


--
-- Name: reservation fkftvilgpq0a4b3mnucdcs3bpv3; Type: FK CONSTRAINT; Schema: public; Owner: washing_machine_center_user
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkftvilgpq0a4b3mnucdcs3bpv3 FOREIGN KEY (machineid) REFERENCES public.washmachine(machineid);


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO washing_machine_center_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO washing_machine_center_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO washing_machine_center_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO washing_machine_center_user;


--
-- PostgreSQL database dump complete
--

\unrestrict T4U91h8k9jY8R0vujXjam733Ug4pxaC6brHkBMy6hqkZpA8YaPaiNFohRM320uP

